### ISSUE TITLE
Minimum stability in composer.json

### ISSUE THREAD

**Issue by cve** [WaveHack/laravel-jade#1]
Hi,

Nice to see that someone have a time to make that package for Laravel 5 :) thank you so much for that, but when I want to use it, the console after runing composer require giving me:

```
[InvalidArgumentException]                                                                                                                                
Could not find package rvanasperen/laravel-jade at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

I know I can change the stability in my composer.json to dev and it should work, but should I?

EDIT:

The above problem occures when I follow readme, but when I put:

```
    "maht0rz/jade": "dev-master",
    "rvanasperen/laravel-jade": "dev-master"
```

into require composer.json then composer update works without any problems.

**Comment by rvanasperen** [comment]
Try putting:

```
"minimum-stability": "dev"
```

In your project composer.json.

**Comment by cve** [comment]
Is it possible to use "extends" and other Jade instructions?

**Comment by rvanasperen** [comment]
What do you mean?

**Comment by cve** [comment]
for example: http://jade-lang.com/reference/extends/

**Comment by rvanasperen** [comment]
The JadePHP package I'm depending on doesn't support 'extends' or 'include', unfortunately. So no.

**Comment by cve** [comment]
Thanks
